[
    {
        "num": 4,
        "endpoint": "http://192.168.1.41:8000",
        "type": "4broadcast",
        "target_id": "vba4"
    },
    {
        "num": 8,
        "endpoint": "http://localhost:8000/tvdata.xml",
        "type": "xmltv",
        "target_id": null
    },
    {
        "num": 10,
        "type": "gracenote",
        "target_id": null
    },
    {
        "num": 12,
        "type": "static",
        "program": {
            "ch_letters": "WX-NOW",
            "titles": [
                "WeatherProbe: Your Local Weather, RIGHT NOW!", 
                "WeatherProbe: Your Weather, NOW!",
                "WeatherProbe: Weather NOW!",
                "WxProbe: Weather NOW!",
                "WxProbe"
            ],
            "episode": "Your Local Weather Information",
            "stars": "*****",
            "year": "2026",
            "program_type": "25",
            "category": "Weather",
            "actor": "Joe WeatherProbe",
            "rating": "TVG",
            "advisories": "Mild storm visuals.",
            "desc": "WeatherProbe is your localized current and forecast weather information available to you any time of day via this channel.",
            "country": "USA",
            "tmsid": "",
            "color": true,
            "stereo": true,
            "captions": false,
            "hd": true
        }
    }
]
