[
    {
        "num": 4,
        "endpoint": "http://192.168.1.41:8000",
        "type": "4broadcast",
        "target_id": "vba4"
    },
    {
        "num": 8,
        "endpoint": "http://localhost:8000",
        "type": "4broadcast",
        "target_id": null
    },
    {
        "num": 10,
        "type": "gracenote",
        "target_id": null
    }
]
