import os
import logging
import datetime as DT
import requests
import xmlproc as XML
import staticproc as STATIC
from common import get_config

PROGRAM_DIR = os.path.dirname(os.path.abspath(__file__))

log = logging.getLogger('spark')



def fetch_guide(endpoint_type:str,endpoint_url:str,date:DT.datetime=None) -> None|str:
    '''Fetches XMLTV (as a string) for the appropriate endpoint and the date provided.'''
    guide = None
    request_url = None
    endpoint_type = endpoint_type.lower() # lowercase for consistency
    try:
        if endpoint_type == "4broadcast":
            # collect API response from 4broadcast
            request_date = date.strftime("%m/%d")
            request_url = f"{endpoint_url}/guide/{request_date}?xmltv=true"
            r = requests.get(request_url, timeout=10)
            r.raise_for_status()
            guide = r.content.decode() # assumes that we received a proper bytestring of XML response
        elif endpoint_type == "ersatz":
            # collect the  raw .xmltv file from //ersatz/iptv/xmltv.xml
            # ersatz generates XMLTV for a day count defined by the operator, we can't target a guide for specific dates. therefore, we'll fetch the same results every time.
            request_url = f"{endpoint_url}/iptv/xmltv.xml"
            #log.debug(request_url)
            r = requests.get(request_url, timeout=10)
            r.raise_for_status()
            guide = r.content.decode()
        elif endpoint_type == "xmltv":
            # a direct link to XMLTV or a direct file path
            # we'll check for "https://" or "http://" at the start, and that'll determine it's a web address.
            if endpoint_url.startswith("https://") or endpoint_url.startswith("http://"):
                log.debug(f"'xmltv' endpoint is web address: {endpoint_url}")
                r = requests.get(endpoint_url, timeout=10)
                r.raise_for_status()
                guide = r.content.decode()
            else: # if not, we just assume it's a file path.
                log.debug(f"'xmltv' endpoint is file path: {endpoint_url}")
                if os.path.exists(endpoint_url):
                    with open(endpoint_url, "r") as f:
                        guide = f.read() 
                        log.debug(f"Retrieved XMLTV guide data from file path '{endpoint_url}'")
                        f.close()
                else:
                    log.error(f"The defined file path for 'xmltv' endpoint was not located at: '{endpoint_url}'")
        elif endpoint_type == "gracenote":
            # the way is this works is by piggy backing off of zap2it-GuideScraping for generation of Gracenote-sourced XMLTV
            # we check for an existing .xmltv file generated by it in the expected path (by date) and if it already exists, just pull from that.
            # if that file does NOT already exist, then we'll use zap2it-GuideScraping to fetch it and then source from the output file.
            request_url = "Gracenote, no URL"
            target_filename = f"gracenote-{date.month}.{date.day}.{date.year}.xmltv"
            cache_folder = os.path.join(PROGRAM_DIR, ".cache") # direct, fixed path
            if not os.path.exists(cache_folder): os.makedirs(cache_folder, exist_ok=True)
            target_path = os.path.join(cache_folder, target_filename) # direct, fixed path
            # initial check - look for a pre-generated XMLTV from z2iGS
            if not os.path.exists(target_path): 
                # we haven't generated this guide from gracenote, let's do it via z2iGS!
                z2iGS_folder_path = os.path.join(PROGRAM_DIR, "zap2it-GuideScraping")
                z2iGS_cfg_path = os.path.join(z2iGS_folder_path, "zap2itconfig.ini")
                if not os.path.exists(z2iGS_cfg_path):
                    log.error(f"Cannot collect from Gracenote: Default zap2it-GuideScraping config file has not yet been defined! ({z2iGS_cfg_path})")
                else:
                    try: # time to attempt to collect via z2iGS. this is happening under a try/except, because any number of exceptions could occur from z2iGS not related to Spark.
                        log.info(f"Attempting to scrape Gracenote for guide data via zap2it-GuideScraping...")
                        os.system(f'cd {z2iGS_folder_path} && py zap2it-GuideScrape.py -o "{target_path}"')
                        if os.path.exists(target_path): log.info(f"Success! XMLTV was dumped as '{target_filename}'.")
                        else: log.error(f"Failed! zap2it-GuideScrape.py did not export an XMLTV file! Please check above for any possible errors.")
                    except:
                        log.error(f"Failed! Something went wrong while running zap2it-GuideScrape.py. See above for errors.",exc_info=False)
            # secondary check - if we have a pre-generated file, load it and return it
            if os.path.exists(target_path):
                with open(target_path, "r") as f:
                    guide = f.read() 
                    log.debug(f"Retrieved Gracenote guide data from '{target_filename}'")
                    f.close()
            else:
                log.error(f"Pre-generated guide file '{target_filename}' does not exist in our cache. Check above to ensure zap2it-GuideScrape.py did not fail.")
    except requests.exceptions.ConnectionError:
        log.error(f"Connection request to '{request_url}' failed!")
    except requests.exceptions.Timeout:
        log.error(f"Connection request to '{request_url}' timed out!")
    except:
        log.error(f"An unhandled error occurred while trying to connect to '{request_url}'",exc_info=True)
    return guide

def parse_and_collect(channels:dict, date:DT.datetime=DT.datetime.now()) -> list:
    '''Parses the channel definitions (channels) and runs the fetch tasks for each and for the specified date. Returns a list of pipe-separated program lines, in the OnCable format.'''
    records = []
    for channel in channels:
        # process the channel number into the OnCable-friendly numbers
        channel_number = channel.get("num", None)
        subchannel = None
        try:
            v = str(float(channel_number)).split(".") # HEHEHE LOL THIS IS DIABOLICAL (but, it works...)
            channel_number = v[0].rjust(3, "0") # (in HU-961 voice) "FIRST DIGIT."
            subchannel = v[1][:1] # (in HU-961 voice) "SECOND DIGIT." - only one digit on the minor channel
            if subchannel == "0": subchannel = None # null it out if there's no subchannel
        except:
            log.warning(f"Invalid value for 'num' in channel definition: {channel}, this definition will be ignored")
            continue # skip this bad definition
        # collect the channel's callsign

        channel_info = {
            "ch_num": channel_number,
            "subch": subchannel,
        }
        # prepare collection for the proper endpoint types
        endpoint_url = channel.get("endpoint", None)
        endpoint_type = channel.get("type", "4broadcast") # assume 4broadcast if unspecified
        endpoint_target = channel.get("target_id", None) # if unspecified, we'll just grab the first channel in XMLTV
        if endpoint_type == "static":
            program_info = channel.get("program", {})
            records.append(STATIC.DICT2DEL(channel_info, program_info, date)) # only one line is generated
        else:
            guide_xml = fetch_guide(endpoint_type, endpoint_url, date)
            if guide_xml:
                records += XML.XMLTV2DEL(guide_xml, endpoint_target, channel_info)
        logdatestr = date.strftime("%m/%d/%Y")
        log.info(f"Built {logdatestr}'s guide data for channel {channel_number}")
    datestr = date.strftime("%m%d%Y")
    filename = f"{datestr}.del"
    return records, filename

def export(records:list,filename:str,cfg:dict):
    '''Exports the Delimited records list to the filename specified, using the directory defined in export.conf.'''
    export_cfg = cfg
    export_dir = export_cfg.get("dir", os.path.join(PROGRAM_DIR, ".export")) # default to local .export if none defined
    if not os.path.exists(export_dir): os.makedirs(export_dir, exist_ok=True)
    export_path = os.path.join(export_dir, filename)
    with open(export_path, "w") as f:
        for line in records:
            f.write(f"{line}\n")
        f.close()
    log.info(f"Successfully exported guide data to '{export_path}'")

def run():
    channels = get_config('channels')
    # Zap2It looks at DEL files 1 day prior, and 4 days beyond the current date
    # however, for now (and since I know this will work anyway), we will just collect yesterday, today, and tomorrow
    dayminus1 = parse_and_collect(channels, date=DT.datetime.now() - DT.timedelta(days=1))
    dayzero = parse_and_collect(channels, date=DT.datetime.now())
    dayplus1 = parse_and_collect(channels, date=DT.datetime.now() + DT.timedelta(days=1))
    # export them
    records = [dayminus1, dayzero, dayplus1]
    export_cfg = get_config('export')
    for r, fname in records:
        export(records=r,filename=fname,cfg=export_cfg)

if __name__ == "__main__":
    import coloredlogs
    coloredlogs.install("DEBUG")
    run()
    